[package]
name = "ptrctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ptr-config = { workspace = true }
ptr-runtime = { workspace = true }
ptr-types = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
ptr-ledger = { workspace = true }
ptr-semdb = { workspace = true }
