//! The runtime's admission machinery, applied to an artifact a model actually
//! wrote.
//!
//! `neural_admission.rs` proves the rules on a payload its own code invented. That
//! leaves one thing unproven: whether the thing a trainer produces is something
//! this runtime can bind at all. The fixture here is a real `ptr-burn-a0`
//! checkpoint — header written by the shared kernel, weights written by burn —
//! regenerated by `model/burn-a0/examples/write_checkpoint.rs`. The two workspaces
//! do not build together, so without it nothing would catch them disagreeing.
use ptr_config::PtrConfig;
use ptr_ledger::integrity;
use ptr_ledger::LedgerEvent;
use ptr_runtime::neural::{Denial, NeuralError, StateDeclaration};
use ptr_runtime::{PtrRuntime, RuntimeError};
use ptr_semdb::SemanticDelta;
use ptr_types::{
    CheckpointError, CheckpointHeader, CodeFamily, Codebook, CodebookVersion, Generation,
    ProvenanceRef,
};

/// The families A0 embeds. Named here rather than imported: `ptr-burn-a0` is an
/// isolated workspace this crate deliberately does not depend on, and `EMBEDDED`
/// in its `checkpoint` module is the same list. The fixture test below fails if
/// they diverge.
const EMBEDDED: [CodeFamily; 3] = [
    CodeFamily::SemanticRole,
    CodeFamily::EpistemicState,
    CodeFamily::ReasoningOperator,
];

const FIXTURE: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/ptr-a0-v1.ckpt"
));

fn runtime() -> PtrRuntime {
    let mut runtime = PtrRuntime::new(PtrConfig::default()).unwrap();
    let mut delta = SemanticDelta::default();
    delta.upserts.insert("plan".into(), "original plan".into());
    runtime
        .apply_semantic_delta(runtime.revision(), delta)
        .unwrap();
    runtime
        .commit(LedgerEvent::CapsuleCommitted {
            project: "p".into(),
            capsule: "capsule:a".into(),
            generation: Generation(1),
        })
        .unwrap();
    runtime
}

fn declaration() -> StateDeclaration {
    StateDeclaration::at(CodebookVersion::V1)
        .reading("plan")
        .under("capsule:a")
        .produced_by(ProvenanceRef {
            source: "trainer:a0".into(),
            note: Some("fixture".to_owned()),
        })
}

/// The fixture's payload, for comparing against what binding retained.
fn fixture_payload() -> Vec<u8> {
    let (_, payload) = CheckpointHeader::read(FIXTURE).expect("the fixture is well formed");
    payload.to_vec()
}

#[test]
fn the_fixture_is_the_artifact_the_model_writes() {
    let (header, payload) = CheckpointHeader::read(FIXTURE).expect("well formed");
    assert_eq!(header.model, "ptr-a0");
    assert_eq!(header.codebook, CodebookVersion::V1);
    assert_eq!(header.codebook_bytes, Codebook::V1.canonical_bytes());
    // The widths the kernel requires, not ones the trainer chose.
    assert_eq!(header.table(CodeFamily::SemanticRole), Some(9));
    assert_eq!(header.table(CodeFamily::EpistemicState), Some(6));
    assert_eq!(header.table(CodeFamily::ReasoningOperator), Some(11));
    header
        .verify(&Codebook::V1, &EMBEDDED)
        .expect("this build's assignment");
    assert!(
        !payload.is_empty(),
        "the fixture must carry real parameters"
    );
}

#[test]
fn a_real_checkpoint_binds_to_committed_state_and_is_admitted() {
    let runtime = runtime();
    let state = runtime
        .bind_checkpoint(FIXTURE, &declaration(), &EMBEDDED)
        .expect("a real checkpoint binds");

    let binding = state.binding();
    assert_eq!(binding.codebook, CodebookVersion::V1);
    assert_eq!(
        binding.codebook_fingerprint,
        integrity::sha256(&Codebook::V1.canonical_bytes()),
        "the fingerprint must come from the assignment, not from the artifact's word"
    );
    assert_eq!(binding.generations.get("capsule:a"), Some(&Generation(1)));
    assert!(binding.semantic_inputs.contains_key("plan"));

    let admitted = runtime.admit(&state).expect("nothing has moved yet");
    assert_eq!(
        admitted.payload(),
        fixture_payload().as_slice(),
        "binding retains the weights, not the header"
    );
}

#[test]
fn a_bound_checkpoint_is_refused_once_the_generation_it_was_bound_under_moves() {
    let mut runtime = runtime();
    let state = runtime
        .bind_checkpoint(FIXTURE, &declaration(), &EMBEDDED)
        .expect("binds");
    runtime.admit(&state).expect("admitted before the move");

    runtime
        .commit(LedgerEvent::CapsuleCommitted {
            project: "p".into(),
            capsule: "capsule:a".into(),
            generation: Generation(2),
        })
        .unwrap();

    assert_eq!(
        runtime
            .admit(&state)
            .expect_err("generation 1 is not a view of generation 2"),
        Denial::StaleGeneration {
            target: "capsule:a".to_owned(),
            bound: Generation(1),
            current: Generation(2),
        }
    );
}

#[test]
fn a_bound_checkpoint_is_refused_once_a_semantic_input_is_edited() {
    let mut runtime = runtime();
    let state = runtime
        .bind_checkpoint(FIXTURE, &declaration(), &EMBEDDED)
        .expect("binds");

    let mut delta = SemanticDelta::default();
    delta.upserts.insert("plan".into(), "edited plan".into());
    runtime
        .apply_semantic_delta(runtime.revision(), delta)
        .unwrap();

    assert_eq!(
        runtime
            .admit(&state)
            .expect_err("the input it read has changed"),
        Denial::EditedInput {
            key: "plan".to_owned()
        }
    );
}

#[test]
fn a_checkpoint_whose_assignment_moved_is_refused_before_it_is_bound() {
    let runtime = runtime();
    let (mut header, payload) = CheckpointHeader::read(FIXTURE).expect("well formed");
    header.codebook_bytes[4] ^= 0x10;
    let moved = header.write(payload);

    let error = runtime
        .bind_checkpoint(&moved, &declaration(), &EMBEDDED)
        .expect_err("the assignment in the artifact is not this build's");
    assert!(
        matches!(
            error,
            RuntimeError::Neural(NeuralError::CheckpointHeader(
                CheckpointError::CodebookMoved { .. }
            ))
        ),
        "expected a moved-assignment refusal, got {error:?}"
    );
    // The untouched fixture still binds, so the refusal is about the assignment.
    runtime
        .bind_checkpoint(FIXTURE, &declaration(), &EMBEDDED)
        .expect("the intact fixture binds");
}

#[test]
fn an_artifact_and_a_declaration_that_disagree_about_the_codebook_are_not_reconciled() {
    let runtime = runtime();
    let (mut header, payload) = CheckpointHeader::read(FIXTURE).expect("well formed");
    header.codebook = CodebookVersion(2);
    let foreign = header.write(payload);

    let error = runtime
        .bind_checkpoint(&foreign, &declaration(), &EMBEDDED)
        .expect_err("v2 weights against a v1 declaration");
    assert_eq!(
        error,
        RuntimeError::Neural(NeuralError::CheckpointCodebook {
            artifact: CodebookVersion(2),
            declared: CodebookVersion::V1,
        })
    );
}

#[test]
fn a_table_that_disagrees_with_the_kernel_is_refused_even_with_the_right_assignment() {
    let runtime = runtime();
    let (header, payload) = CheckpointHeader::read(FIXTURE).expect("well formed");
    let mut narrowed = header.clone();
    narrowed.tables[0].rows = 8;
    let error = runtime
        .bind_checkpoint(&narrowed.write(payload), &declaration(), &EMBEDDED)
        .expect_err("eight slot types is not nine semantic roles");
    assert_eq!(
        error,
        RuntimeError::Neural(NeuralError::CheckpointHeader(CheckpointError::TableSize {
            family: CodeFamily::SemanticRole,
            stored: 8,
            required: 9,
        }))
    );
}

#[test]
fn every_prefix_of_the_fixture_is_refused() {
    let runtime = runtime();
    for length in [0, 1, 7, 8, 9, 32, 128, FIXTURE.len() / 2, FIXTURE.len() - 1] {
        let error = runtime
            .bind_checkpoint(&FIXTURE[..length], &declaration(), &EMBEDDED)
            .err()
            .unwrap_or_else(|| panic!("a prefix of {length} bytes must not bind"));
        assert!(
            matches!(
                error,
                RuntimeError::Neural(NeuralError::CheckpointHeader(_))
            ),
            "prefix of {length} bytes gave {error:?}"
        );
    }
}

#[test]
fn naming_no_family_still_checks_the_assignment_the_codes_belong_to() {
    // A consumer that does not know which families a model embeds still must not
    // be able to bind an artifact from a moved assignment.
    let runtime = runtime();
    runtime
        .bind_checkpoint(FIXTURE, &declaration(), &[])
        .expect("the assignment is this build's");

    let (mut header, payload) = CheckpointHeader::read(FIXTURE).expect("well formed");
    header.codebook_bytes.push(0);
    assert!(runtime
        .bind_checkpoint(&header.write(payload), &declaration(), &[])
        .is_err());
}

#[test]
fn a_bound_checkpoint_retains_its_binding_through_a_seal_and_reopen() {
    // "The checkpoint records a StateBinding" is this: the artifact a trainer
    // writes carries its assignment, and the retained form carries the committed
    // facts as well, so a later process re-checks rather than re-asserts.
    let runtime = runtime();
    let state = runtime
        .bind_checkpoint(FIXTURE, &declaration(), &EMBEDDED)
        .expect("binds");
    let sealed = state.seal().expect("a bound checkpoint seals");

    let reopened = ptr_runtime::neural::NeuralState::open(sealed.bytes(), sealed.anchor())
        .expect("its own seal reopens");
    assert_eq!(reopened.binding(), state.binding());
    assert_eq!(
        runtime
            .admit(&reopened)
            .expect("still admissible")
            .payload(),
        fixture_payload().as_slice(),
        "the weights must survive the round trip unchanged"
    );
}
