[package]
name = "ptrd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ptr-config = { workspace = true }
ptr-runtime = { workspace = true }
ptr-server = { workspace = true }
ptr-model-api = { workspace = true }
ptr-pods = { workspace = true }
ptr-router = { workspace = true }
ptr-ledger = { workspace = true }
ptr-types = { workspace = true }
tokio = { workspace = true }
