"""Write datasets/generated/codebook.json from the kernel's own tables.

Anything outside Rust that needs the cognitive codebook — dataset validation
today, a training loader tomorrow — reads this file. The alternative is retyping
the tables, which is the duplication `ptr-types::Codebook` exists to prevent: a
Python set that disagrees with the Rust enum fails nothing until a checkpoint
means something different than it says.

The Rust example prints the tables and the canonical bytes; the fingerprint is
computed here, because `ptr-types` has no dependencies and therefore no hasher.
`crates/ptr-types/tests/codebook_artifact.rs` then asserts that the committed
file still carries the bytes the kernel produces, so drift fails in the ordinary
test run rather than at the next release.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "datasets/generated/codebook.json"


def emit() -> dict:
    completed = subprocess.run(
        ["cargo", "run", "-q", "-p", "ptr-types", "--example", "codebook"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(completed.stdout)


def build(document: dict) -> dict:
    canonical = bytes.fromhex(document["canonical_bytes_hex"])
    document["fingerprint_sha256"] = hashlib.sha256(canonical).hexdigest()
    document["note"] = (
        "Generated by scripts/generate_codebook.py from ptr-types. Do not edit by "
        "hand: crates/ptr-types/tests/codebook_artifact.rs fails when this file "
        "and the kernel disagree, and scripts/check_codebook.py fails when the "
        "fingerprint does not match the bytes recorded beside it."
    )
    return document


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()

    try:
        document = build(emit())
    except subprocess.CalledProcessError as error:
        print(f"error: the codebook example failed: {error.stderr}", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    families = len(document["families"])
    members = sum(len(family["members"]) for family in document["families"])
    print(f"{args.out}: version {document['version']}, {families} families, {members} members")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
