"""Write research/falsification/A0-ablations-v1/RESULTS.md from the aggregate.

Every number comes from results.json (written by scripts/aggregate_a0_ablation.py),
the per-experiment results/a0_internal_metrics.json, references.json, budget.json
and criteria.toml; no number is transcribed by hand. Every verdict is reported,
nulls, HARMFUL and INCONCLUSIVE ones included, with its reason and its per-seed
numbers. The interpretation is prose, and each of its sentences is written only
for the verdicts it describes; the section on what happened after the freeze is
a hand-written record of this run, marked as such. Each FALSIFIES or HARMFUL
verdict also gets a FALSIFIED-<contrast>.md note, as research/falsification/
README.md asks ("Record negative results").
"""

from __future__ import annotations

import json
import statistics
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STUDY = ROOT / "research/falsification/A0-ablations-v1"
EXPERIMENTS = {
    "M001": "model/M001-semantic-slots",
    "M002": "model/M002-typed-attention",
    "M003": "model/M003-latent-recurrence",
    "M004": "model/M004-operator-router",
}
SPLITS = ["test_iid", "ood_compose_epi", "ood_compose_regime", "ood_distractors", "ood_validity", "ood_payload"]
MECHANISM = {
    "M001-primary": "typed slot content",
    "M001-secondary": "typed slot content with admission",
    "M002-necessity": "the rank-1 typed attention bias",
    "M002-sufficiency": "the typed attention bias as the only metadata-dependent read",
    "M003-depth": "a second tied refinement step",
}


def f(value, digits=4) -> str:
    """Format report values, using an em dash for None and fixed precision for floats."""
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def main() -> int:
    """Render study verdicts, gates, tables, and interpretation into RESULTS.md."""
    results = json.loads((STUDY / "results.json").read_text(encoding="utf-8"))
    references = json.loads((STUDY / "references.json").read_text(encoding="utf-8"))
    budget = json.loads((STUDY / "budget.json").read_text(encoding="utf-8"))
    criteria = tomllib.loads((STUDY / "criteria.toml").read_text(encoding="utf-8"))
    composite_a = criteria["composites"]["A"]
    contrasts = {c["id"]: c for c in criteria["contrast"]}
    scale = f"one block, d_model {budget['d_model']}, {budget['steps']} steps"
    metrics, later_metrics = {}, {}
    for experiment, path in EXPERIMENTS.items():
        document = json.loads((ROOT / "experiments" / path / "results/a0_internal_metrics.json").read_text(encoding="utf-8"))
        for arm, by_seed in document["arms"].items():
            metrics[arm] = by_seed
        for arm, by_seed in document.get("contingency_arms", {}).items():
            later_metrics[arm] = by_seed
    below_bar = {arm for arm, status in results.get("learnability", {}).items() if not status["passes"]}

    def seed_mean(table: dict, arm: str, split: str, subset: str | None = None) -> float:
        """Average an arm's split or subset accuracy across the available seeds."""
        by_seed = table[arm].values()
        if subset is None:
            return statistics.fmean(scores[split]["route_accuracy"] for scores in by_seed)
        return statistics.fmean(scores[split]["subsets"][subset]["accuracy"] for scores in by_seed)

    out: list[str] = []
    w = out.append
    w("# A0 mechanism ablation study v1: results")
    w("")
    w("Generated by `scripts/report_a0_ablation.py` from `results.json` (the output of `scripts/aggregate_a0_ablation.py` applying the frozen `criteria.toml`), the per-experiment `results/a0_internal_metrics.json` and `references.json`. Preregistration: commit 45b2d54 (`PREREGISTRATION.md`). Scope: an A0-internal ablation on the synthetic benchmark operator-routing v1; it is not the M001-M004 manifests' baseline comparisons, and it says nothing about language-model quality.")
    w("")
    w("## Verdicts")
    w("")
    w("| Contrast | Verdict | Reason |")
    w("|---|---|---|")
    for cid, entry in results["verdicts"].items():
        w(f"| {cid} | **{entry.get('verdict')}** | {entry.get('reason', '')} |")
    if "summary" in results:
        w("")
        w(results["summary"])
    w("")
    w("## Gates")
    w("")
    w("| Gate | Pass | Detail |")
    w("|---|---|---|")
    for name in sorted(results["gates"]):
        gate = results["gates"][name]
        w(f"| {name} | {'yes' if gate['pass'] else '**NO**'} | `{json.dumps(gate['detail'], sort_keys=True)[:300]}` |")
    leak = results.get("leak_alarm")
    if leak:
        w("")
        w(f"Leak alarm: {'**ACTIVE**' if leak['active'] else 'inactive'} (raw-blind mean test_iid {f(leak['raw_blind_mean_test_iid'])}, exact ceiling {f(leak['ceiling'])}).")
    cross = results.get("stock_aggregate_cross_check")
    if cross:
        w("")
        w(f"Stock `run_experiment.py aggregate` cross-check: {'agrees to 1e-12' if cross['pass'] else 'MISMATCH ' + ', '.join(cross['mismatches'])}.")
    w("")
    w("## Learnability")
    w("")
    w("| Arm | Kind | Mean test_iid | Bar | Passes |")
    w("|---|---|---:|---:|---|")
    for arm, status in results.get("learnability", {}).items():
        w(f"| {arm} | {status['kind']} | {f(status['mean_test_iid'])} | {f(status['bar'])} | {'yes' if status['passes'] else '**no**'} |")
    rescued = results.get("reported", {}).get("contingency")
    if rescued:
        w("")
        w(f"### Contingency at {rescued['steps']} steps")
        w("")
        w("Same seeds, learning rates and data; only the step count differs. Each arm is held to the same bar as at S*.")
        w("")
        w("| Arm | Mean test_iid | Bar | Passes | Per-seed test_iid | Mean composite A |")
        w("|---|---:|---:|---|---|---:|")
        for arm, status in rescued["arms"].items():
            w(f"| {arm} | {f(status['mean_test_iid'])} | {f(status['bar'])} | {'yes' if status['passes'] else '**no**'} | "
              f"{', '.join(f'{v:.3f}' for v in status['test_iid'])} | {statistics.fmean(status['composite_A']):.4f} |")
    w("")
    w("## Accuracy by arm and split (mean over the five seeds, with the range)")
    w("")
    w("| Arm | " + " | ".join(SPLITS) + " |")
    w("|---|" + "---:|" * len(SPLITS))
    for arm, by_seed in metrics.items():
        cells = []
        for split in SPLITS:
            values = [by_seed[s][split]["route_accuracy"] for s in by_seed]
            cells.append(f"{statistics.fmean(values):.4f} ({min(values):.3f}-{max(values):.3f})")
        w(f"| {arm} | " + " | ".join(cells) + " |")
    refs = references["references"]
    w("")
    w("Reference lines on the same splits, for comparison: " + "; ".join(
        f"{name} {f(refs[key]['test_iid'])} on test_iid"
        for key, name in [("bound_additive", "bound additive"), ("hand_weighted", "hand-weighted"),
                          ("raw_blind_exact_bayes", "raw-blind exact Bayes ceiling"), ("train_majority", "train-majority")]
    ) + ".")
    w("")
    w("## Contrasts in detail")
    for cid, entry in results["verdicts"].items():
        if "stats" not in entry:
            continue
        stats = entry["stats"]
        w("")
        w(f"### {cid}: {entry['verdict']}")
        w("")
        w(f"Endpoint `{entry['endpoint']}`. Per-seed delta (comparator - ablated): {', '.join(f'{d:+.4f}' for d in stats['deltas'])}. Mean {stats['mean']:+.4f}, SD {stats['sd']:.4f}, 95% t-interval [{stats['ci'][0]:+.4f}, {stats['ci'][1]:+.4f}], {stats['positive_seeds']}/5 seeds positive.")
        if entry.get("note"):
            w(f"*{entry['note']}.*")
        if "attribution_stats" in entry:
            a = entry["attribution_stats"]
            w(f"Attribution (full - latent-linear): mean {a['mean']:+.4f}, 95% t-interval [{a['ci'][0]:+.4f}, {a['ci'][1]:+.4f}], {a['positive_seeds']}/5 positive; component verdicts {entry['component_verdicts']}; latent-linear - latent-0 {entry['linear_minus_zero']:+.4f}.")
        if "mask_share" in entry:
            at = entry.get("mask_share_budget", "S*")
            why = " (the contingency did not re-run the masked arm, so no share exists at the budget that decided the verdict)" if at == "S*" and entry.get("note") else ""
            undertrained = " At S* no-semantic-slots is below its learnability bar, so this share mixes the mask with undertraining." if at == "S*" and "no-semantic-slots" in below_bar else ""
            w(f"Mask share of the gap (no-semantic-slots-masked - no-semantic-slots on the endpoint), at {at}: {entry['mask_share']:+.4f}{why}.{undertrained}")
        if "dose_response" in entry:
            w(f"Dose response (latent-4): {entry['dose_response']}.")
        if "deterministic_reference" in entry:
            d = entry["deterministic_reference"]
            margin = contrasts[cid]["deterministic_margin"]
            w(f"Learned routing against the designer's deterministic router (hand-weighted {f(d['hand_weighted_test_iid'])} on test_iid): full arm min {f(d['full_min'])}, max {f(d['full_max'])}; the preregistered claim 'learned beats deterministic by {round(100 * margin)} points on every seed' {d['learned_beats_deterministic']}.")
            if "frozen-router" in metrics:
                frozen_min = min(scores["test_iid"]["route_accuracy"] for scores in metrics["frozen-router"].values())
                if frozen_min >= d["hand_weighted_test_iid"] + margin:
                    w(f"The frozen-router arm, whose readout is never trained, clears the same margin (lowest seed {frozen_min:.4f}), so the margin comes from the learned layers before the readout, not from learning the router.")
                else:
                    w(f"The frozen-router arm, whose readout is never trained, has lowest seed {frozen_min:.4f} on test_iid.")
    reported = results.get("reported", {})
    if "mask_effect" in reported:
        m = reported["mask_effect"]
        w("")
        w("## Reported without a verdict")
        w("")
        w(f"The admission mask on its own (no-semantic-slots-masked - no-semantic-slots, at S*): {m['validity_decisive_test_iid']:+.4f} on the validity-decisive subset of test_iid, {m['ood_validity']:+.4f} on ood_validity.")
        if m.get("below_learnability_bar"):
            caveat = f"This difference is not the mask's effect alone: at S* {', '.join(m['below_learnability_bar'])} is below its learnability bar, so it also measures undertraining."
            if "no-semantic-slots" in later_metrics and "no-semantic-slots-masked" not in later_metrics:
                caveat += (
                    f" At {results['reported']['contingency']['steps']} steps the unmasked arm alone reaches "
                    f"{seed_mean(later_metrics, 'no-semantic-slots', 'ood_validity'):.4f} on ood_validity and "
                    f"{seed_mean(later_metrics, 'no-semantic-slots', 'test_iid', 'validity'):.4f} on the validity-decisive subset, "
                    f"above the masked arm's {seed_mean(metrics, 'no-semantic-slots-masked', 'ood_validity'):.4f} and "
                    f"{seed_mean(metrics, 'no-semantic-slots-masked', 'test_iid', 'validity'):.4f} at S*. "
                    "The masked arm was not re-run, so the mask's own effect at matched training is unknown."
                )
            w("")
            w(caveat)
    if "transfer" in reported:
        w("")
        w("Compositional transfer (descriptive; the strict transfer subset of ood_compose_regime, where every no-transfer reference scores 0, and the held-out pairs of ood_compose_epi):")
        w("")
        w("| Arm | New role x regime cell | Per-seed strict transfer accuracy | Held-out pairs | Per-seed heldout accuracy |")
        w("|---|---|---|---|---|")
        for arm, t in reported["transfer"].items():
            w(f"| {arm} | {t['new_role_regime_cell']} | {', '.join(f'{v:.3f}' for v in t['strict_transfer'])} | {t['heldout_pairs']} | {', '.join(f'{v:.3f}' for v in t['heldout'])} |")
    w("")
    w("## After the freeze: what happened, in order")
    w("")
    w("*A hand-written record of this run, not derived from the aggregate.*")
    w("")
    w("- The lr-selection commit (4b0ad16) held only `lr_selection.*` and the sweep records. The evaluation, the rerun and the contingency all ran from it with a clean worktree; gate G4 checks every one of those records and the diff from the tag to that commit.")
    secondary = results["verdicts"].get("M001-secondary", {})
    learn = results.get("learnability", {}).get("no-semantic-slots")
    if learn and not learn["passes"]:
        w(f"- `no-semantic-slots` fell below its learnability bar at S* ({learn['mean_test_iid']:.4f} < {learn['bar']:.4f}), which triggered the preregistered contingency: that arm and `full` re-run at 4000 steps with the same seeds and learning rates. M001-secondary is decided on those runs." + (
            f" There the arm cleared the bar ({rescued['arms']['no-semantic-slots']['mean_test_iid']:.4f} >= {learn['bar']:.4f})."
            if rescued and rescued["arms"].get("no-semantic-slots", {}).get("passes") else ""))
    w("- The aggregator as frozen did not re-check the learnability bar on the 4000-step runs, which the criteria require (an arm still below it makes the contrast INCONCLUSIVE). It was fixed in commit bd84b48 after the contingency runs finished and before any of their results were read, with a test that fails against the frozen code; the criteria did not change.")
    w("- A mistake in process, recorded for completeness: while the contingency's first three processes were running, the fix was briefly present as an uncommitted edit, which would have marked any process started then as dirty. It was stashed before the remaining two processes started; all five contingency records show `git_dirty = false` at 4b0ad16.")
    w("- After the results were read, an independent review found gaps in the gates and the report. G0 and G2 could pass on empty input; G3, G4 and G5 looked only at the evaluation records, not at the rerun and the contingency; G4 did not check the diff from the tag; a failed process's scores could have entered a table; and some of this report's prose was written for this outcome. The commits after 7bc4060 close each gap. No table and no verdict changed, and the aggregator as it stood at the tag, applied to the same tables, gives the same nine verdicts.")
    w("- A known deviation of no consequence: the learning-rate schedule ends at 0.1000011 x peak on the last step rather than exactly 0.1 x peak (`examples/a0_ablation/train.rs`: the cosine progress reaches (S-101)/(S-100), not 1). It is the same for every arm.")
    w("- The preregistration tag `a0-ablation-prereg-v1` points at 45b2d54. It exists in the working copy the study ran in; this session could push the branch but not tags, so recreate it with `git tag a0-ablation-prereg-v1 45b2d54` before re-running the aggregator elsewhere.")
    w("")
    w("## Interpretation (not a rule output)")
    w("")
    primary = results["verdicts"].get("M001-primary", {})

    def composite_at_s_star(arm: str) -> float:
        """Average composite-A split accuracies over seeds at the original training budget."""
        return statistics.fmean(
            statistics.fmean(by_split[split]["route_accuracy"] for split in composite_a)
            for by_split in metrics[arm].values()
        )

    verdict_of = {cid: entry.get("verdict") for cid, entry in results["verdicts"].items()}
    if (verdict_of.get("M001-primary") == "SUPPORTS" and secondary.get("note") == "decided at 4000 steps"
            and verdict_of.get("M001-secondary") != "SUPPORTS" and rescued and secondary.get("stats")):
        later = {arm: statistics.fmean(status["composite_A"]) for arm, status in rescued["arms"].items()}
        w(f"Typed slot content helped at the preregistered budget: on the OOD composite A the full arm beat the masked content-free arm by {primary['stats']['mean']:+.4f} on average at {budget['steps']} steps. "
          f"The contingency qualifies that. Given {rescued['steps']} steps, the unmasked content-free arm, which must bind every fact from index-tagged raw tokens and learn the Live gate itself, "
          f"rose from {composite_at_s_star('no-semantic-slots'):.4f} to {later['no-semantic-slots']:.4f} on composite A, while the full arm stayed at {composite_at_s_star('full'):.4f} and {later['full']:.4f}; "
          f"the gap closed to {secondary['stats']['mean']:+.4f} (interval [{secondary['stats']['ci'][0]:+.4f}, {secondary['stats']['ci'][1]:+.4f}]). "
          f"At {budget['steps']} steps the masked arm scored {composite_at_s_star('no-semantic-slots-masked'):.4f} there; it was not re-run at {rescued['steps']} steps, so M001-primary's margin is known only at {budget['steps']}. "
          "Much of what typed slots buy in this task may therefore be learning speed rather than a capability the raw path lacks; a study at matched longer budgets for every arm would separate the two.")
    else:
        w(f"M001-primary is {verdict_of.get('M001-primary')} and M001-secondary is {verdict_of.get('M001-secondary')}"
          + (f" ({secondary['note']})" if secondary.get("note") else "") + "; see their details above.")
    nulls = [cid for cid, v in verdict_of.items() if v == "FALSIFIES" and cid in MECHANISM]
    harmful = [cid for cid, v in verdict_of.items() if v == "HARMFUL" and cid in MECHANISM]
    sentences = []
    if nulls:
        names = [MECHANISM[cid] for cid in nulls]
        thresholds = sorted({contrasts[cid]["delta_min"] for cid in nulls})
        threshold = " or ".join(f"{round(100 * t)} points" for t in thresholds)
        sentences.append(f"For {' and for '.join(names)}, a benefit of {threshold} or more is excluded at this scale ({', '.join(nulls)}); "
                         f"{'each is a candidate' if len(nulls) > 1 else 'it is a candidate'} for simplification.")
    if harmful:
        sentences.append(f"Removing {' and '.join(MECHANISM[cid] for cid in harmful)} made A0 better ({', '.join(harmful)}).")
    nonlinearity = results["verdicts"].get("M003-nonlinearity", {})
    if nonlinearity.get("verdict") == "SUPPORTS-NONLINEARITY":
        sentences.append(f"The per-slot nonlinearity is used: removing the latent step costs {100 * nonlinearity['stats']['mean']:.1f} points on test_iid, and removing only its gelu costs {100 * nonlinearity['attribution_stats']['mean']:.1f}.")
    elif nonlinearity.get("verdict"):
        sentences.append(f"M003-nonlinearity is {nonlinearity['verdict']}: {nonlinearity.get('reason', '')}.")
    router = verdict_of.get("M004-negative-control")
    sentences.append({
        "INCONCLUSIVE": "The frozen router could not be shown equivalent to the learned one within the preregistered band, and nothing about routing follows from it either way.",
        "EQUIVALENT": "The frozen router is equivalent to the learned one within the preregistered band, as predicted; nothing about routing follows from it.",
        "SUPPORTS": "The paired design detected a difference between the frozen and the learned router, two models equivalent up to reparameterisation; this is a probable optimisation artefact, and effects near 2 points elsewhere must be read with it in mind.",
        "HARMFUL": "The frozen router did better than the learned one, which points at an optimisation effect rather than at routing.",
    }.get(router, f"The negative control is {router}."))
    w("")
    w(" ".join(sentences))
    w("")
    w("## Reading these results")
    w("")
    w(f"Every verdict holds only for this A0 ({scale}) on operator-routing v1, a synthetic task whose label rule was written to have the same form as A0's admitted-mean router. Nothing here is evidence about language-model quality, and nothing here is the M001-M004 baseline comparison, which needs the plain model baseline (owner decision O2). `PREREGISTRATION.md` lists the deviations from the design and what the study cannot show.")
    (STUDY / "RESULTS.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    # A note belongs to the current verdicts only: an earlier aggregate's note for a
    # contrast that is no longer a null would otherwise survive.
    for stale in STUDY.glob("FALSIFIED-*.md"):
        stale.unlink()
    for cid, entry in results["verdicts"].items():
        if entry.get("verdict") not in ("FALSIFIES", "HARMFUL"):
            continue
        stats = entry["stats"]
        note = [
            f"# Falsified in A0: {cid}",
            "",
            f"**Verdict:** {entry['verdict']}. {entry['reason'][:1].upper() + entry['reason'][1:]}.",
            "",
            f"**Evidence:** endpoint `{entry['endpoint']}`, five declared seeds, paired on seed. Per-seed delta (comparator - ablated): {', '.join(f'{d:+.4f}' for d in stats['deltas'])}; mean {stats['mean']:+.4f}; 95% t-interval [{stats['ci'][0]:+.4f}, {stats['ci'][1]:+.4f}], whose upper bound is below the preregistered minimum effect. All gates passed. Details: `RESULTS.md`, `results.json`.",
            "",
            f"**Scope:** A0 ({scale}) on the synthetic operator-routing v1. It does not show the mechanism is useless elsewhere, only that "
            + ("removing it made A0 better here." if entry["verdict"] == "HARMFUL" else "it bought nothing measurable here."),
            "",
            "**Consequence, per research/falsification/README.md:** the component is a candidate for removal or redesign in A0; the target is not redefined.",
        ]
        (STUDY / f"FALSIFIED-{cid}.md").write_text("\n".join(note) + "\n", encoding="utf-8")
    print(STUDY / "RESULTS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
