"""Write research/falsification/A0-ablations-v1/RESULTS.md from the aggregate.

Every number comes from results.json (written by scripts/aggregate_a0_ablation.py),
the per-experiment results/a0_internal_metrics.json, references.json, budget.json
and criteria.toml; nothing is transcribed by hand. Every verdict is reported,
nulls, HARMFUL and INCONCLUSIVE ones included, with its reason and its per-seed
numbers. Each FALSIFIES or HARMFUL verdict also gets a FALSIFIED-<contrast>.md
note, as research/falsification/README.md asks ("Record negative results").
"""

from __future__ import annotations

import json
import statistics
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STUDY = ROOT / "research/falsification/A0-ablations-v1"
EXPERIMENTS = {
    "M001": "model/M001-semantic-slots",
    "M002": "model/M002-typed-attention",
    "M003": "model/M003-latent-recurrence",
    "M004": "model/M004-operator-router",
}
SPLITS = ["test_iid", "ood_compose_epi", "ood_compose_regime", "ood_distractors", "ood_validity", "ood_payload"]


def f(value, digits=4) -> str:
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def main() -> int:
    results = json.loads((STUDY / "results.json").read_text(encoding="utf-8"))
    references = json.loads((STUDY / "references.json").read_text(encoding="utf-8"))
    budget = json.loads((STUDY / "budget.json").read_text(encoding="utf-8"))
    composite_a = tomllib.loads((STUDY / "criteria.toml").read_text(encoding="utf-8"))["composites"]["A"]
    scale = f"one block, d_model {budget['d_model']}, {budget['steps']} steps"
    metrics = {}
    for experiment, path in EXPERIMENTS.items():
        document = json.loads((ROOT / "experiments" / path / "results/a0_internal_metrics.json").read_text(encoding="utf-8"))
        for arm, by_seed in document["arms"].items():
            metrics[arm] = by_seed

    out: list[str] = []
    w = out.append
    w("# A0 mechanism ablation study v1: results")
    w("")
    w("Generated by `scripts/report_a0_ablation.py` from `results.json` (the output of `scripts/aggregate_a0_ablation.py` applying the frozen `criteria.toml`), the per-experiment `results/a0_internal_metrics.json` and `references.json`. Preregistration: commit 45b2d54 (`PREREGISTRATION.md`). Scope: an A0-internal ablation on the synthetic benchmark operator-routing v1; it is not the M001-M004 manifests' baseline comparisons, and it says nothing about language-model quality.")
    w("")
    w("## Verdicts")
    w("")
    w("| Contrast | Verdict | Reason |")
    w("|---|---|---|")
    for cid, entry in results["verdicts"].items():
        w(f"| {cid} | **{entry.get('verdict')}** | {entry.get('reason', '')} |")
    if "summary" in results:
        w("")
        w(results["summary"])
    w("")
    w("## Gates")
    w("")
    w("| Gate | Pass | Detail |")
    w("|---|---|---|")
    for name in sorted(results["gates"]):
        gate = results["gates"][name]
        w(f"| {name} | {'yes' if gate['pass'] else '**NO**'} | `{json.dumps(gate['detail'], sort_keys=True)[:300]}` |")
    leak = results.get("leak_alarm")
    if leak:
        w("")
        w(f"Leak alarm: {'**ACTIVE**' if leak['active'] else 'inactive'} (raw-blind mean test_iid {f(leak['raw_blind_mean_test_iid'])}, exact ceiling {f(leak['ceiling'])}).")
    cross = results.get("stock_aggregate_cross_check")
    if cross:
        w("")
        w(f"Stock `run_experiment.py aggregate` cross-check: {'agrees to 1e-12' if cross['pass'] else 'MISMATCH ' + ', '.join(cross['mismatches'])}.")
    w("")
    w("## Learnability")
    w("")
    w("| Arm | Kind | Mean test_iid | Bar | Passes |")
    w("|---|---|---:|---:|---|")
    for arm, status in results.get("learnability", {}).items():
        w(f"| {arm} | {status['kind']} | {f(status['mean_test_iid'])} | {f(status['bar'])} | {'yes' if status['passes'] else '**no**'} |")
    rescued = results.get("reported", {}).get("contingency")
    if rescued:
        w("")
        w(f"### Contingency at {rescued['steps']} steps")
        w("")
        w("Same seeds, learning rates and data; only the step count differs. Each arm is held to the same bar as at S*.")
        w("")
        w("| Arm | Mean test_iid | Bar | Passes | Per-seed test_iid | Mean composite A |")
        w("|---|---:|---:|---|---|---:|")
        for arm, status in rescued["arms"].items():
            w(f"| {arm} | {f(status['mean_test_iid'])} | {f(status['bar'])} | {'yes' if status['passes'] else '**no**'} | "
              f"{', '.join(f'{v:.3f}' for v in status['test_iid'])} | {statistics.fmean(status['composite_A']):.4f} |")
    w("")
    w("## Accuracy by arm and split (mean over the five seeds, with the range)")
    w("")
    w("| Arm | " + " | ".join(SPLITS) + " |")
    w("|---|" + "---:|" * len(SPLITS))
    for arm, by_seed in metrics.items():
        cells = []
        for split in SPLITS:
            values = [by_seed[s][split]["route_accuracy"] for s in by_seed]
            cells.append(f"{statistics.fmean(values):.4f} ({min(values):.3f}-{max(values):.3f})")
        w(f"| {arm} | " + " | ".join(cells) + " |")
    refs = references["references"]
    w("")
    w("Reference lines on the same splits, for comparison: " + "; ".join(
        f"{name} {f(refs[key]['test_iid'])} on test_iid"
        for key, name in [("bound_additive", "bound additive"), ("hand_weighted", "hand-weighted"),
                          ("raw_blind_exact_bayes", "raw-blind exact Bayes ceiling"), ("train_majority", "train-majority")]
    ) + ".")
    w("")
    w("## Contrasts in detail")
    for cid, entry in results["verdicts"].items():
        if "stats" not in entry:
            continue
        stats = entry["stats"]
        w("")
        w(f"### {cid}: {entry['verdict']}")
        w("")
        w(f"Endpoint `{entry['endpoint']}`. Per-seed delta (comparator - ablated): {', '.join(f'{d:+.4f}' for d in stats['deltas'])}. Mean {stats['mean']:+.4f}, SD {stats['sd']:.4f}, 95% t-interval [{stats['ci'][0]:+.4f}, {stats['ci'][1]:+.4f}], {stats['positive_seeds']}/5 seeds positive.")
        if entry.get("note"):
            w(f"*{entry['note']}.*")
        if "attribution_stats" in entry:
            a = entry["attribution_stats"]
            w(f"Attribution (full - latent-linear): mean {a['mean']:+.4f}, 95% t-interval [{a['ci'][0]:+.4f}, {a['ci'][1]:+.4f}], {a['positive_seeds']}/5 positive; component verdicts {entry['component_verdicts']}; latent-linear - latent-0 {entry['linear_minus_zero']:+.4f}.")
        if "mask_share" in entry:
            at = entry.get("mask_share_budget", "S*")
            why = " (the contingency did not re-run the masked arm, so no share exists at the budget that decided the verdict)" if at == "S*" and entry.get("note") else ""
            w(f"Mask share of the gap (no-semantic-slots-masked - no-semantic-slots on the endpoint), at {at}: {entry['mask_share']:+.4f}{why}.")
        if "dose_response" in entry:
            w(f"Dose response (latent-4): {entry['dose_response']}.")
        if "deterministic_reference" in entry:
            d = entry["deterministic_reference"]
            w(f"Learned routing against the designer's deterministic router (hand-weighted {f(d['hand_weighted_test_iid'])} on test_iid): full arm min {f(d['full_min'])}, max {f(d['full_max'])}; the claim 'learned beats deterministic by 5 points on every seed' {d['learned_beats_deterministic']}.")
    reported = results.get("reported", {})
    if "mask_effect" in reported:
        m = reported["mask_effect"]
        w("")
        w("## Reported without a verdict")
        w("")
        w(f"The admission mask on its own (no-semantic-slots-masked - no-semantic-slots): {m['validity_decisive_test_iid']:+.4f} on the validity-decisive subset of test_iid, {m['ood_validity']:+.4f} on ood_validity.")
    if "transfer" in reported:
        w("")
        w("Compositional transfer (descriptive; the strict transfer subset of ood_compose_regime, where every no-transfer reference scores 0, and the held-out pairs of ood_compose_epi):")
        w("")
        w("| Arm | New role x regime cell | Per-seed strict transfer accuracy | Held-out pairs | Per-seed heldout accuracy |")
        w("|---|---|---|---|---|")
        for arm, t in reported["transfer"].items():
            w(f"| {arm} | {t['new_role_regime_cell']} | {', '.join(f'{v:.3f}' for v in t['strict_transfer'])} | {t['heldout_pairs']} | {', '.join(f'{v:.3f}' for v in t['heldout'])} |")
    w("")
    w("## After the freeze: what happened, in order")
    w("")
    w("- The lr-selection commit (4b0ad16) held only `lr_selection.*` and the sweep records. The evaluation, the rerun and the contingency all ran from it with a clean worktree: gate G4 checks the evaluation records, and the rerun and contingency records show the same commit and `git_dirty = false`.")
    secondary = results["verdicts"].get("M001-secondary", {})
    learn = results.get("learnability", {}).get("no-semantic-slots")
    if learn and not learn["passes"]:
        w(f"- `no-semantic-slots` fell below its learnability bar at S* ({learn['mean_test_iid']:.4f} < {learn['bar']:.4f}), which triggered the preregistered contingency: that arm and `full` re-run at 4000 steps with the same seeds and learning rates. M001-secondary is decided on those runs." + (
            f" There the arm cleared the bar ({rescued['arms']['no-semantic-slots']['mean_test_iid']:.4f} >= {learn['bar']:.4f})."
            if rescued and rescued["arms"].get("no-semantic-slots", {}).get("passes") else ""))
    w("- The aggregator as frozen did not re-check the learnability bar on the 4000-step runs, which the criteria require (an arm still below it makes the contrast INCONCLUSIVE). It was fixed in commit bd84b48 after the contingency runs finished and before any of their results were read, with a test that fails against the frozen code; the criteria did not change.")
    w("- A mistake in process, recorded for completeness: while the contingency's first three processes were running, the fix was briefly present as an uncommitted edit, which would have marked any process started then as dirty. It was stashed before the remaining two processes started; all five contingency records show `git_dirty = false` at 4b0ad16.")
    w("- The preregistration tag `a0-ablation-prereg-v1` points at 45b2d54. It exists in the working copy the study ran in; this session could push the branch but not tags, so recreate it with `git tag a0-ablation-prereg-v1 45b2d54` before re-running the aggregator elsewhere.")
    w("")
    w("## Interpretation (not a rule output)")
    w("")
    primary = results["verdicts"].get("M001-primary", {})

    def composite_at_s_star(arm: str) -> float:
        return statistics.fmean(
            statistics.fmean(by_split[split]["route_accuracy"] for split in composite_a)
            for by_split in metrics[arm].values()
        )

    if primary.get("stats") and secondary.get("stats") and rescued:
        later = {arm: statistics.fmean(status["composite_A"]) for arm, status in rescued["arms"].items()}
        w(f"Typed slot content helped at the preregistered budget: on the OOD composite A the full arm beat the masked content-free arm by {primary['stats']['mean']:+.4f} on average at {budget['steps']} steps. "
          f"The contingency qualifies that. Given {rescued['steps']} steps, the unmasked content-free arm, which must bind every fact from index-tagged raw tokens and learn the Live gate itself, "
          f"rose from {composite_at_s_star('no-semantic-slots'):.4f} to {later['no-semantic-slots']:.4f} on composite A, while the full arm stayed at {composite_at_s_star('full'):.4f} and {later['full']:.4f}; "
          f"the gap closed to {secondary['stats']['mean']:+.4f} (interval [{secondary['stats']['ci'][0]:+.4f}, {secondary['stats']['ci'][1]:+.4f}]). "
          f"At {budget['steps']} steps the masked arm scored {composite_at_s_star('no-semantic-slots-masked'):.4f} there; it was not re-run at {rescued['steps']} steps, so M001-primary's margin is known only at {budget['steps']}. "
          "Much of what typed slots buy in this task may therefore be learning speed rather than a capability the raw path lacks; a study at matched longer budgets for every arm would separate the two.")
    nonlinearity = results["verdicts"].get("M003-nonlinearity", {})
    if nonlinearity.get("stats") and nonlinearity.get("attribution_stats"):
        w("")
        w(f"For the typed attention bias and for a second tied refinement step, a benefit of 2 points or more is excluded at this scale, as the design expected for the first; both are candidates for simplification. "
          f"The per-slot nonlinearity, by contrast, is used: removing the latent step costs {100 * nonlinearity['stats']['mean']:.1f} points on test_iid, and removing only its gelu costs {100 * nonlinearity['attribution_stats']['mean']:.1f}. "
          "The frozen router could not be shown equivalent to the learned one within the preregistered band, and nothing about routing follows from it either way.")
    w("")
    w("## Reading these results")
    w("")
    w(f"Every verdict holds only for this A0 ({scale}) on operator-routing v1, a synthetic task whose label rule was written to have the same form as A0's admitted-mean router. Nothing here is evidence about language-model quality, and nothing here is the M001-M004 baseline comparison, which needs the plain model baseline (owner decision O2). `PREREGISTRATION.md` lists the deviations from the design and what the study cannot show.")
    (STUDY / "RESULTS.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    # A note belongs to the current verdicts only: an earlier aggregate's note for a
    # contrast that is no longer a null would otherwise survive.
    for stale in STUDY.glob("FALSIFIED-*.md"):
        stale.unlink()
    for cid, entry in results["verdicts"].items():
        if entry.get("verdict") not in ("FALSIFIES", "HARMFUL"):
            continue
        stats = entry["stats"]
        note = [
            f"# Falsified in A0: {cid}",
            "",
            f"**Verdict:** {entry['verdict']}. {entry['reason'][:1].upper() + entry['reason'][1:]}.",
            "",
            f"**Evidence:** endpoint `{entry['endpoint']}`, five declared seeds, paired on seed. Per-seed delta (comparator - ablated): {', '.join(f'{d:+.4f}' for d in stats['deltas'])}; mean {stats['mean']:+.4f}; 95% t-interval [{stats['ci'][0]:+.4f}, {stats['ci'][1]:+.4f}], whose upper bound is below the preregistered minimum effect. All gates passed. Details: `RESULTS.md`, `results.json`.",
            "",
            f"**Scope:** A0 ({scale}) on the synthetic operator-routing v1. It does not show the mechanism is useless elsewhere, only that it bought nothing measurable here.",
            "",
            "**Consequence, per research/falsification/README.md:** the component is a candidate for removal or redesign in A0; the target is not redefined.",
        ]
        (STUDY / f"FALSIFIED-{cid}.md").write_text("\n".join(note) + "\n", encoding="utf-8")
    print(STUDY / "RESULTS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
